"use client";

import { useActionState } from "react";
import { createCorrectionRequestAction, createLeaveRequestAction, type AttendanceActionState } from "./actions";
import { useCloseOnSuccess } from "../dashboard/form-dialog";

const initialState: AttendanceActionState = { error: "", fieldErrors: {} };
export default function AttendanceRequestForm({ mode, onCancel, onSaved }: { mode: "leave" | "correction"; onCancel: () => void; onSaved: () => void }) {
  const [state, action, pending] = useActionState(mode === "leave" ? createLeaveRequestAction : createCorrectionRequestAction, initialState);
  useCloseOnSuccess(pending, state, onSaved);
  const described = (field: string) => state.fieldErrors[field] ? { "aria-describedby": `${field}-error`, "aria-invalid": true as const } : {};
  const error = (field: string) => state.fieldErrors[field] ? <small className="client-form-error" id={`${field}-error`}>{state.fieldErrors[field]}</small> : null;
  return <form action={action} className="client-editor-form attendance-request-form"><section className="client-form-section"><div><p className="eyebrow">{mode === "leave" ? "LEAVE REQUEST" : "ATTENDANCE CORRECTION"}</p><h2>{mode === "leave" ? "Leave request" : "Attendance correction"}</h2><span>{mode === "leave" ? "Submit planned or unplanned leave for manager review." : "Propose a correction without overwriting the original attendance record."}</span></div><div className="client-form-grid">
    {mode === "leave" ? <><label><span>From</span><input {...described("dateFrom")} name="dateFrom" required type="date" />{error("dateFrom")}</label><label><span>To</span><input {...described("dateTo")} name="dateTo" required type="date" />{error("dateTo")}</label><label><span>Leave type</span><select {...described("leaveType")} defaultValue="casual" name="leaveType"><option value="casual">Casual</option><option value="sick">Sick</option><option value="earned">Earned</option><option value="maternity">Maternity</option><option value="compensatory">Compensatory</option><option value="other">Other</option></select>{error("leaveType")}</label><label><span>Duration</span><select {...described("dayPortion")} defaultValue="full" name="dayPortion"><option value="full">Full day</option><option value="first_half">First half</option><option value="second_half">Second half</option></select>{error("dayPortion")}</label><label><span>Pay classification</span><select {...described("paidClassification")} defaultValue="paid" name="paidClassification"><option value="paid">Paid leave</option><option value="unpaid">Unpaid leave</option></select>{error("paidClassification")}</label></> : <><label><span>Attendance date</span><input {...described("attendanceDate")} name="attendanceDate" required type="date" />{error("attendanceDate")}</label><label><span>Proposed status</span><select {...described("proposedStatus")} defaultValue="present" name="proposedStatus"><option value="present">Present</option><option value="half_day">Half day</option><option value="late">Late</option><option value="wfh">Work from home</option><option value="tour">Client duty / tour</option><option value="leave">Leave</option><option value="absent">Absent</option></select>{error("proposedStatus")}</label><label><span>Proposed check-in</span><input {...described("proposedCheckInTime")} name="proposedCheckInTime" type="time" />{error("proposedCheckInTime")}</label><label><span>Proposed check-out</span><input {...described("proposedCheckOutTime")} name="proposedCheckOutTime" type="time" />{error("proposedCheckOutTime")}</label></>}
    <label className="client-form-wide"><span>Reason</span><textarea {...described("reason")} maxLength={500} name="reason" placeholder="Explain the request for the reviewer." required rows={5} />{error("reason")}</label>
  </div></section>{state.error && <p className="client-form-banner" role="alert">{state.error}</p>}<div className="client-form-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancel</button><button className="primary-button" disabled={pending} type="submit">{pending ? "Submitting..." : "Submit request"}</button></div></form>;
}
